#[".config/fish"]
#type = "git-repo"
#url = "https://github.com/bode-fun/fish-conf.git"
##refreshPeriod = "48h"

[".config/bat/themes/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/bat.git"
refreshPeriod = "336h"
